[package]
name = "wl_drm"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
wayland-client.workspace = true
wayland-scanner.workspace = true
wayland-server.workspace = true
