name: CI

on:
  push:
    branches: [ "main", "ci-revamp-test" ]
  pull_request:
    branches: [ "main", "ci-revamp-test" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v5
      - name: Get MSRV
        id: msrv
        run: echo "msrv=$(
          awk '/^rust-version = "[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+"$/ {
            print substr($NF, 2, length($NF) - 2)
          }' Cargo.toml)" >> "$GITHUB_OUTPUT"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xwayland clang libxcb1 libxcb-cursor0 libxcb-cursor-dev curl pkg-config libegl1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.msrv.outputs.msrv }}
      - uses: Swatinem/rust-cache@v2
      - name: Check workspace
        run: cargo check --profile ci --locked --verbose --keep-going --workspace --exclude xwayland-satellite
      - name: Build
        run: cargo test --no-run --profile ci --locked --verbose
      - name: Run tests
        run: cargo test --profile ci --locked --verbose --no-fail-fast -- --test-threads 1
      - name: Format check
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy --profile ci --locked --workspace --all-targets
