name: CI

on:
  push:
    branches: [ "main", "ci-revamp-test" ]
  pull_request:
    branches: [ "main", "ci-revamp-test" ]

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  UBUNTU_DOCKERFILE: .github/workflows/ubuntu.dockerfile

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: Cargo.toml
      - name: Get commit timestamp
        run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> "$GITHUB_ENV"
      - name: Get MSRV
        run: echo "MSRV=$(
          awk '/^rust-version = "[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+"$/ {
            print substr($NF, 2, length($NF) - 2)
          }' Cargo.toml)" >> "$GITHUB_ENV"
      - id: container-path
        run: echo "path=${{ env.REGISTRY }}/${GITHUB_REPOSITORY@L}" >> "$GITHUB_OUTPUT"
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Creates a docker-container builder, since it has the power to cache to and from registry.
      - uses: docker/setup-buildx-action@v3
        id: registry-builder
      - uses: docker/build-push-action@v6
        id: docker-build-push-registry
        with:
          builder: ${{ steps.registry-builder.outputs.name }}
          file: ${{ env.UBUNTU_DOCKERFILE }}
          tags: ${{ steps.container-path.outputs.path }}-ubuntu:latest
          labels: org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          cache-from: type=registry,ref=${{ steps.container-path.outputs.path }}-ubuntu:cache
          cache-to: |
            ${{ github.event_name == 'push' &&
            format('type=registry,ref={0}-ubuntu:cache,mode=max', steps.container-path.outputs.path) ||
            '' }}
          outputs: type=image,push=${{ github.event_name == 'push' }}
      # Creating a docker builder to extract the Docker image because it is ~40 seconds faster than
      # extracting it through the docker-container builder, well, at long as it does not rebuild
      - uses: docker/setup-buildx-action@v3
        id: image-builder
        with:
          driver: docker
      - uses: docker/build-push-action@v6
        id: docker-build-push-image
        with:
          builder: ${{ steps.image-builder.outputs.name }}
          file: ${{ env.UBUNTU_DOCKERFILE }}
          labels: org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          cache-from: ${{ steps.registry-builder.outputs.imageid }}
          outputs: type=docker
      - name: Start container
        run: docker run --name xwls-test --detach --interactive --tty
          ${{ steps.docker-build-push-image.outputs.imageid }}
      - name: Check workspace
        run: docker exec --interactive xwls-test
          sh -c "cargo check --profile ci --locked --verbose --keep-going --workspace --exclude xwayland-satellite"
      - name: Build
        run: docker exec --interactive xwls-test
          sh -c "cargo test --no-run --profile ci --locked --verbose"
      - name: Run tests
        run: docker exec --interactive xwls-test
          sh -c "cargo test --profile ci --locked --verbose --no-fail-fast -- --test-threads 1"
      - name: Format check
        run: docker exec --interactive xwls-test
          sh -c "cargo fmt --check"
      - name: Clippy
        run: docker exec --interactive xwls-test
          sh -c "cargo clippy --profile ci --locked --workspace --all-targets"
